import { useState, useEffect, useCallback } from 'react';
import Head from 'next/head';
import BlockProduct from '../components/BlockProduct';
import MarqueeProduct from '../components/MarqueeProduct';
import { apiGet } from '../helpers/api'

export default function Home(props) {
  const [products, setProducts] = useState([]);

  const getProuct = useCallback(async () => {
    const res = await apiGet('https://fakestoreapi.com/products?limit=5');
    setProducts(res);
  }, [])

  useEffect(() => {
    getProuct();
  }, [])
  return (
    <div className="w-full min-h-screen ">
      <Head>
        <title>Eton ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full">
        <BlockProduct products={products} />
        <MarqueeProduct />
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  return { props: {} }
}